# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='stepcount',
            old_name='user_id',
            new_name='user',
        ),
    ]
