# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stepserver', '0002_auto_20180327_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=200)),
                ('index', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak_id', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('median', models.IntegerField(default=0)),
                ('n_active_day', models.IntegerField(default=0)),
                ('n_inactive_day', models.IntegerField(default=0)),
                ('p_500_5k', models.FloatField(default=0)),
                ('p_5k_10k', models.FloatField(default=0)),
                ('p_10k_105k', models.FloatField(default=0)),
                ('p_105k', models.FloatField(default=0)),
                ('slope', models.FloatField(default=0)),
                ('cov', models.FloatField(default=0)),
                ('autocorrelation', models.FloatField(default=0)),
                ('trend', models.FloatField(default=0)),
                ('skewness', models.FloatField(default=0)),
                ('kurtosis', models.FloatField(default=0)),
                ('days_since_last_prize', models.IntegerField(default=0)),
                ('points_till_next_prize', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepserver.User')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stepserver.Question'),
        ),
    ]
