# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepserver', '0002_auto_20180322_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stepcount',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
