# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepserver', '0006_streakinfo_has_bad_prediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streak',
            name='autocorrelation',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='cohort_end_date',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='cohort_start_date',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='cov',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='days_since_last_prize',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='kurtosis',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='median',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='n_active_day',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='n_inactive_day',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='p_105k',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='p_10k_105k',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='p_500_5k',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='p_5k_10k',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='points_till_next_prize',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='skewness',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='slope',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='streak',
            name='trend',
        ),
        migrations.AddField(
            model_name='streak',
            name='calendar_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='streak',
            name='cohort_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='streak',
            name='step_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stepcount',
            name='date',
            field=models.DateField(default=datetime.date(2018, 4, 17)),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 4, 17)),
        ),
    ]
