# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stepserver', '0007_auto_20180417_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streak',
            old_name='streak_id',
            new_name='streak_cluster_id',
        ),
    ]
