# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 12:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stepserver', '0009_userclustergroupinfo_userclusterinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepcount',
            name='date',
            field=models.DateField(default=datetime.date(2018, 5, 3)),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 5, 3)),
        ),
    ]
